- name: Install RISC-V toolchain for cross-compiling. See https://wiki.debian.org/RISC-V
  hosts: localhost

  tasks:
  - name: Install packages with dnf
    become: yes
    ansible.builtin.dnf:
      name:
        # required for user mode emulation
        - qemu-user-static
        - qemu-user-binfmt
        # gcc
        - gcc-riscv64-linux-gnu
